# NBA Arena Explorer - Setup Script
# This script helps you set up the project for the first time

Write-Host "🏀 NBA Arena Explorer - Setup Assistant" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if local.properties exists
$localPropertiesPath = "local.properties"
if (Test-Path $localPropertiesPath) {
    Write-Host "✅ local.properties file found" -ForegroundColor Green
    
    # Check if MAPS_API_KEY is present
    $content = Get-Content $localPropertiesPath -Raw
    if ($content -match "MAPS_API_KEY=") {
        if ($content -match "MAPS_API_KEY=YOUR_API_KEY_HERE" -or $content -match "MAPS_API_KEY=\s*$") {
            Write-Host "⚠️  MAPS_API_KEY found but not configured" -ForegroundColor Yellow
            Write-Host "   Please add your Google Maps API key to local.properties" -ForegroundColor Yellow
            Write-Host "   See GOOGLE_MAPS_SETUP.md for detailed instructions" -ForegroundColor Yellow
        } else {
            Write-Host "✅ MAPS_API_KEY is configured" -ForegroundColor Green
        }
    } else {
        Write-Host "❌ MAPS_API_KEY not found in local.properties" -ForegroundColor Red
        Write-Host "   Adding MAPS_API_KEY placeholder..." -ForegroundColor Yellow
        Add-Content $localPropertiesPath "`nMAPS_API_KEY=YOUR_API_KEY_HERE"
        Write-Host "   Please replace YOUR_API_KEY_HERE with your actual API key" -ForegroundColor Yellow
    }
} else {
    Write-Host "❌ local.properties file not found" -ForegroundColor Red
    Write-Host "   Creating local.properties file..." -ForegroundColor Yellow
    
    # Get Android SDK path from environment
    $androidHome = $env:ANDROID_HOME
    if (-not $androidHome) {
        $androidHome = "$env:LOCALAPPDATA\Android\Sdk"
    }
    
    # Create local.properties with SDK path and API key placeholder
    $sdkPath = $androidHome -replace '\\', '\\'
    $localPropertiesContent = @"
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.

sdk.dir=$sdkPath

# Google Maps API Key
# Get your key from: https://console.cloud.google.com/
# See GOOGLE_MAPS_SETUP.md for detailed instructions
MAPS_API_KEY=YOUR_API_KEY_HERE
"@
    
    Set-Content $localPropertiesPath $localPropertiesContent
    Write-Host "✅ local.properties file created" -ForegroundColor Green
    Write-Host "   Please replace YOUR_API_KEY_HERE with your actual Google Maps API key" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "📚 Setup Resources:" -ForegroundColor Cyan
Write-Host "   • README.md - Project overview and usage guide" -ForegroundColor White
Write-Host "   • GOOGLE_MAPS_SETUP.md - Detailed API key setup instructions" -ForegroundColor White
Write-Host "   • instructions.md - Assignment requirements" -ForegroundColor White
Write-Host ""

Write-Host "🚀 Next Steps:" -ForegroundColor Cyan
Write-Host "   1. Get your Google Maps API key (see GOOGLE_MAPS_SETUP.md)" -ForegroundColor White
Write-Host "   2. Add the key to local.properties: MAPS_API_KEY=your_key_here" -ForegroundColor White
Write-Host "   3. Open project in Android Studio" -ForegroundColor White
Write-Host "   4. Click 'Sync Project with Gradle Files'" -ForegroundColor White
Write-Host "   5. Build and run the app!" -ForegroundColor White
Write-Host ""

Write-Host "✅ Setup assistant complete!" -ForegroundColor Green
Write-Host ""
